name: polylog
description: "PolyLog helps you build language skills through journaling and AI feedback"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  hooks_riverpod: ^2.6.1

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  firebase_app_check: ^0.3.0

  # Routing
  go_router: ^14.2.7

  # Localization
  intl: ^0.20.2

  # Utilities
  collection: ^1.18.0
  diff_match_patch: ^0.4.1
  shared_preferences: ^2.3.2
  uuid: ^4.4.0
  flutter_markdown: ^0.7.5
  google_sign_in: ^6.2.1
  flutter_heatmap_calendar: ^1.0.5
  firebase_crashlytics: ^4.3.10
  cloud_functions: ^5.6.2
  path_provider: ^2.1.5
  ffi: ^2.1.4
  http: ^1.5.0
  crypto: ^3.0.6
  url_launcher: ^6.3.2
  google_mlkit_translation: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/translations/

flutter_launcher_icons:
  image_path: "assets/polylog1.jpg"
  android: true
  ios: true

flutter_native_splash:
  image: assets/polylog1.jpg
  color: "#FFFFFF"
  android: true
  ios: true
  android_12:
    image: assets/polylog1.jpg
    color: "#FFFFFF"
